### ISSUE TITLE
[Crypto] Add LBRY Credits

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#10]
Please add the ability to trade between Monero and LBRY Credits (LBC).

LBRY Credits can only be obtained from centralized exchanges or from having an Odysee account which both require KYC. By adding LBRY credits, one can buy LBRY credits with privacy and interact in the LBRY network by having a private/anonymous channel on LBRY or donate to content creators on LBRY with more privacy.

https://coinmarketcap.com/currencies/library-credits/markets/

https://lbry.com/

**Comment by HavenoDEX** [comment]
This issue has been transferred to the [dedicated repository](https://github.com/haveno-dex/listing) for asset listing. Please edit the issue according to the correct [issue template](https://github.com/haveno-dex/listing/tree/master/.github/ISSUE_TEMPLATE)

**Comment by HavenoDEX** [comment]
No answer from the Author. Closing.
