### ISSUE TITLE
[Fiat] Add BRL Real Brazil

### ISSUE THREAD

**Issue by wrbraga** [haveno-dex/listing#15]
- [ x] I confirm there are no other issues about this asset (open or closed)
- [ x] I understand that Haveno expects the project applying for being listed to take care of the PR for the actual implementation
- [x ] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ticker symbol of the project?

BRL

### Why should it be added to Haveno? How would it benefit the project and the community?
The Brazilian cryptocurrency market is one of the most significant and important. Big exchanges like Binance and Coinbase are coming here.

## Where is the currency used?
Binance, Coinbase/Mercado Bitcoin

## Why would Haveno be beneficial for the people using this specific fiat currency?
The number of Brazilian users would help with liquidity.

**Comment by HavenoDEX** [comment]
https://github.com/haveno-dex/haveno-site/pull/83
