### ISSUE TITLE
[Rupee] Add <INR>

### ISSUE THREAD

**Issue by Mark8021** [haveno-dex/listing#17]
- [X ] I confirm there are no other issues about this asset (open or closed)
- [x ] I understand that Haveno expects the project applying for being listed to take care of the PR for the actual implementation
- [ x] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ticker symbol of the project?
<INR>

### Why should it be added to Haveno? How would it benefit the project and the community?
Public exposure 

## Where is the currency used?

India

**Comment by HavenoDEX** [comment]
https://github.com/haveno-dex/haveno-site/pull/83
