### ISSUE TITLE
[Fiat] Add <NAME OF THE ASSET> Gold and Silver Bullions

### ISSUE THREAD

**Issue by Moneder0** [haveno-dex/listing#18]
- [ X] I confirm there are no other issues about this asset (open or closed)
- [X ] I understand that Haveno expects the project applying for being listed to take care of the PR for the actual implementation
- [X ] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ticker symbol of the project?

Don't remember :-)

### Why should it be added to Haveno? How would it benefit the project and the community?
It could bring extra liquidity apart from cash

## Where is the currency used?
Worldwide

## Why would Haveno be beneficial for the people using this specific fiat currency?
It would be an excellent alternative for fiat

### Additional notes
I'm fully aware that adding metals would be tricky the least, but a good start could be only accepting the very well known standard bullions (1 Oz. Eagles, Buffalo and Maple coins for instance)

**Comment by HavenoDEX** [comment]
Thanks for opening the issue @Moneder0, but the possibility of listing precious metals is something that needs to be investigated first, to assess feasibility. I'm closing this issue as it's not practically actionable now, please continue the discussion here: https://github.com/haveno-dex/haveno/issues/229 :)

**Comment by RunnyBabbit** [comment]
> 

1)  The standard ISO currency code for gold is XAU — not "AU", as this poster indicated (by the way, it's "XAG" for silver)

2) "XAU" has an international weight & purity standard of 1 oz at 24k purity (99.999% purity)

3) There's nothing complicated about gold or silver bullion trading; it's the exact same as any other currency trading pair — coins with an extra collectable premium are known as "numismatic" coins, and are completely irrelevant to the bullion (ie, melt) trading value of common XAU & XAG ounce bars & coins

4) COUNTERFEITING:  Like fiat paper, assaying the purity of precious metals is the responsibility of the sellee — there is no practical difference in counterparty risk, or in assaying fiat currencies, or assaying metal monies

5) Reputation ratings already solve Number 4 — no need to make the non-issue seem more complicated than it is; worst case, have sellers check a box that they have assayed the metal (or have run an anti-counterfeit marker across the fiat currency) before releasing the Monero from escrow — this easily solves the non-problem, arbitration-wise

6)  LocalMonero added this arbitrary request to recognize "Gold (XAU)" (and "Silver (XAG)") currencies within 10 minutes of the first public Twitter request — precedent exists, and it's a trivial no-risk addition to add real monies as accepted currencies

7) Due their inherent fungibility & industrial uses, precious metals are a CBDC-proof on-ramp & off-ramp into both Monero & fiat (even as fiat becomes completely digital & programmable)

8) Unlike fiat currencies, gold & silver are international currencies that are universally recognized & honored by the people of all nations — even if those people's governments are repressive or totalitarian

9) I can't believe I have to defend adding gold & silver as accepted currencies — seriously
