### ISSUE TITLE
[Fiat] Add Australian dollars (AUD)

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#2]
Please consider down the road adding the ability to exchange between Monero and Australian Dollars (AUD) and allowing one to price things in AUD.

**Comment by HavenoDEX** [comment]
This issue has been transferred to the [dedicated repository](https://github.com/haveno-dex/listing) for asset listing. Please edit the issue according to the correct [issue template](https://github.com/haveno-dex/listing/tree/master/.github/ISSUE_TEMPLATE)

**Comment by HavenoDEX** [comment]
No answer from the Author. Closing.
