### ISSUE TITLE
[Fiat] Add Swiss Franc CHF

### ISSUE THREAD

**Issue by sonalder-darlene** [haveno-dex/listing#23]
- [X] I confirm there are no other issues about this asset (open or closed)
- [X] I understand that Haveno expects the project applying for being listed to take care of the PR for the actual implementation
- [X] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ticker symbol of the project?
CHF

### Why should it be added to Haveno? How would it benefit the project and the community?
Swiss Franc is (obviously) the most used currency in Switzerland. In that country you can buy Monero at ATM (no KYC) with cash and a small fee. So I assume the Monero community in Switzerland is present

## Where is the currency used?
Switzerland (rich people LoL)
Liechstenstein

## Why would Haveno be beneficial for the people using this specific fiat currency?
Haveno could have some of this sweet money the swiss people have.

### Additional notes
I know it represent a small amount of people but Swiss privacy-minded people are numberous for the size of the country. It could also help privacy oriented organisation and company based in Switzerland acccept Monero. As a Monero user I assume you know they are some.

**Comment by HavenoDEX** [comment]
https://github.com/haveno-dex/haveno-site/pull/83
