### ISSUE TITLE
[Fiat] Add Canadian Dollars

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#25]
### What's the ISO code of the currency?
CAD

### Why should it be added to Haveno? How would it benefit the project and the community?
Canada has a population around 40 million people.

Canada has many different crypto exchanges

## Where is the currency used?
Canada

## Why would Haveno be beneficial for the people using this specific fiat currency?
Canadians can easily use Haveno and exhcnage with other Canadians

**Comment by HavenoDEX** [comment]
Please acknowledge the statements at the top of the template.
