### ISSUE TITLE
[Fiat] Add Australian Dollar

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#26]
### What's the ISO code of the currency?
AUD

### Why should it be added to Haveno? How would it benefit the project and the community?
Australia has a population around 25 million people.

Australia is far from other major countries in the world and will be easier to trade amongst others in Australia.

## Where is the currency used?
Australia

## Why would Haveno be beneficial for the people using this specific fiat currency?
Australians can easily use Haveno and exhcnage with other Australians

**Comment by HavenoDEX** [comment]
Please acknowledge the statements at the top of the template.
