### ISSUE TITLE
[Fiat] Add Canadian Dollars (CAD)

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#3]
Please consider down the road adding the ability to exchange between Monero and Canadian Dollars (CAD) and allowing one to price things in CAD.

**Comment by HavenoDEX** [comment]
This issue has been transferred to the [dedicated repository](https://github.com/haveno-dex/listing) for asset listing. Please edit the issue according to the correct [issue template](https://github.com/haveno-dex/listing/tree/master/.github/ISSUE_TEMPLATE)

**Comment by HavenoDEX** [comment]
No answer from the Author. Closing.
