### ISSUE TITLE
[Fiat] Add Canadian Dollars

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#33]
- [x] I confirm there are no other open issues about this asset
- [x] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ISO code of the currency?
CAD

### Why should it be added to Haveno? How would it benefit the project and the community?
Canada has a population around 40 million people.

Canada has many different crypto exchanges

## Where is the currency used?
Canada

## Why would Haveno be beneficial for the people using this specific fiat currency?
Canadians can easily use Haveno and exhcnage with other Canadians

### Additional notes
None

**Comment by HavenoDEX** [comment]
https://github.com/haveno-dex/haveno-site/pull/83
