### ISSUE TITLE
[Fiat] Add Australian Dollar

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#34]
- [X] I confirm there are no other open issues about this asset
- [X] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### Why should it be added to Haveno? How would it benefit the project and the community?
Australia has a population around 25 million people.

Australia is far from other major countries in the world and will be easier to trade amongst others in Australia.

## Where is the currency used?
Australia

## Why would Haveno be beneficial for the people using this specific fiat currency?
Australians can easily use Haveno and exhcnage with other Australians 

### Additional notes
None

**Comment by HavenoDEX** [comment]
https://github.com/haveno-dex/haveno-site/pull/83
