### ISSUE TITLE
[Crypto] Add Terra

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#4]
Please consider down the road adding Terra and all of its stable assets to be exchanged between Monero.

**Comment by HavenoDEX** [comment]
This issue has been transferred to the [dedicated repository](https://github.com/haveno-dex/listing) for asset listing. Please edit the issue according to the correct [issue template](https://github.com/haveno-dex/listing/tree/master/.github/ISSUE_TEMPLATE)

**Comment by HavenoDEX** [comment]
No answer from the Author. Closing.
