### ISSUE TITLE
[Fiat] Add Silver

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#45]
- [X] I confirm there are no other open issues about this asset
- [X] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ISO code of the currency?
AG

### Why should it be added to Haveno? How would it benefit the project and the community?
High-value, low difficulty feature request for adding silver as currency options within Haveno

Adding this functionality would be huge for XMR adoption, liquidity & utility — particularly to the 'Free Staters' in New Hampshire (the largest Monero & hard money parallel economy in the world), and create new private, fungible, sound-money, non-KYC/AML avenues for customers & vendors to on-ramp/off-ramp into the Monero ecosystem

## Where is the currency used?
Worldwide

## Why would Haveno be beneficial for the people using this specific fiat currency?
Silver is physical sound money which has been around for thousands of years.

### Additional notes
Silver is denominated in grams & troy ounces.

Issues still open on this in haveno github repository
https://github.com/haveno-dex/haveno/issues/229

**Comment by HavenoDEX** [comment]
See https://github.com/haveno-dex/listing/issues/18#issuecomment-1115997071
