### ISSUE TITLE
[Crypto] Add Siacoin

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#5]
Please consider down the road adding the ability to exchange between Monero and Siacoin.

Siacoin aka Sia is a decentralized cloud storage network. Currently there are no DEXes that support swapping Sia to Monero or Monero to Sia. Sia is the best or at least one of the best cloud storage coins/projects in the crypto space.

https://sia.tech/

**Comment by HavenoDEX** [comment]
This issue has been transferred to the [dedicated repository](https://github.com/haveno-dex/listing) for asset listing. Please edit the issue according to the correct [issue template](https://github.com/haveno-dex/listing/tree/master/.github/ISSUE_TEMPLATE)

**Comment by nahuhh** [comment]
@trymeouteh 
Siacoin is already on the list

**Comment by erciccione** [comment]
@nahuhh Siafund is different from siacoin.

**Comment by HavenoDEX** [comment]
No answer from the Author. Closing.
