### ISSUE TITLE
[Crypto] Add Terra

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#52]
- [X] I confirm there are no other open issues about this asset
- [X] I understand that to actually add the asset to Haveno, a PR from the developers/community of the proposed asset might be necessary
- [X] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ticker symbol of the project?
LUNA

### Why should it be added to Haveno? How would it benefit the project and the community?
A stablecoin ecosystem being integrated into Haveno allows for stability in the Haveno DEX. Terra is the most popular stablecoin ecosystem and the stablecoins are synthetic and not backed 1 to 1 were trust is required unlike Tether stablecoins.

### Is it an Ethereum token (ERC-20)?

- [ ] Yes
- [X] No

### Was the coin pre-mined before public launch?

- [X] Yes
- [ ] No

### Is there a dev fee for the project maintainers?

- [ ] Yes
- [X] No

### Please provide resources about the project (Website, Twitter, etc)
https://www.terra.money/

### Additional notes
None

**Comment by dginovker** [comment]
Aged like milk
