### ISSUE TITLE
[Crypto] Add UST

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#53]
- [X] I confirm there are no other open issues about this asset
- [X] I understand that to actually add the asset to Haveno, a PR from the developers/community of the proposed asset might be necessary
- [X] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ticker symbol of the project?
UST

### Why should it be added to Haveno? How would it benefit the project and the community?
A US stablecoin is key. UST is synthetic and requires no trust unlike Teather USDT which is backed 1 to 1.

### Is it an Ethereum token (ERC-20)?

- [ ] Yes
- [X] No

### Was the coin pre-mined before public launch?

- [X] Yes
- [ ] No

Terra LUNA was premined.

### Is there a dev fee for the project maintainers?

- [ ] Yes
- [X] No

### Please provide resources about the project (Website, Twitter, etc)
https://www.terra.money/

### Additional notes
None

**Comment by NotIshanSingh** [comment]
Such a stable coin!

**Comment by trymeouteh** [comment]
> Such a stable coin!

Yeah no kidding, after opening this I then realised LUNA and UST is crashing.

**Comment by Gonbatfire** [comment]
> Yeah no kidding, after opening this I then realised LUNA and UST is crashing.

ouch.
