### ISSUE TITLE
[Fiat] Add JPY (Japanese Yen)

### ISSUE THREAD

**Issue by Farzat07** [haveno-dex/listing#56]
- [x] I confirm there are no other open issues about this asset
- [x] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ISO code of the currency?

JPY

### Why should it be added to Haveno? How would it benefit the project and the community?
It should help with the adoption in Japan, as the govenment legally bans exchanges from listing it.

## Where is the currency used?
Japan.

## Why would Haveno be beneficial for the people using this specific fiat currency?
Centralized exchanges can't list XMR in Japan. People buying in JPY can only rely on decentralized exchanges.

**Comment by HavenoDEX** [comment]
https://github.com/haveno-dex/haveno-site/pull/83
