### ISSUE TITLE
[Crypto] Add OXEN

### ISSUE THREAD

**Issue by mdPlusPlus** [haveno-dex/listing#57]
- [X] I confirm there are no other open issues about this asset
- [X] I understand that to actually add the asset to Haveno, a PR from the developers/community of the proposed asset might be necessary
- [X] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ticker symbol of the project?

OXEN

### Why should it be added to Haveno? How would it benefit the project and the community?
It's a "privacy coin" and was forked from Monero. The project has built an anonymous overlay network (Lokinet) and an anonymous messenger (Session, a decentralized fork of Signal). Oxen incorporates the same priciples as Haveno, and therefore Haveno could gain new privacy-conscious users that currently aren't aware of Haveno. According to coinmarketcap.com there currently is a daily trading volume of around $500,000 to $3,000,000 and most of it would probably rather be exchanged on a private alternative like Haveno. Also, since Haveno users are already interested in privacy, they might start getting into Oxen and generate trading fees for the platform.

Personally, I'd just really like to see both projects, Haveno and Oxen, to succeed.

### Is it an Ethereum token (ERC-20)?

- [ ] Yes
- [X] No

### Was the coin pre-mined before public launch?

- [X] Yes (https://loki.network/2018/05/16/loki-premine-report/)
- [ ] No

### Is there a dev fee for the project maintainers?

- [X] Yes (Current discussion: https://github.com/oxen-io/oxen-improvement-proposals/issues/29)
- [ ] No

### Please provide resources about the project (Website, Twitter, etc)
Collection of lots of links: https://oxen.directory  

Official links:
 - https://oxen.io/
 - https://getsession.org/
 - https://lokinet.org/
 - https://www.youtube.com/c/OxenNetwork
 - https://optf.ngo/
 - https://t.me/Oxen_Community
 - https://twitter.com/Oxen_io
 - https://twitter.com/session_app
 - https://twitter.com/Lokinet_org
 - https://open.getsession.org/ (Open groups on Session messenger)

### Additional notes
 - Founded in 2018
 - Original name was Loki, was renamed to Oxen later
 - Monero fork
 - Originally PoW, but transitioned to PoS
 - The Session messenger has over a million downloads on Play Store
 - The Oxen Privacy Tech Foundation (OPTF) is based in Australia
 - There are currently around ~1800 Oxen Service Nodes (nodes that have reached their full staking potential of 15000 OXEN)
 - There's a decentralized name service, the Oxen Name Service, similar to DNS

**Comment by djHenryStackz** [comment]
Let's do this OXEN has specifically got my attention,

A Monero fork, POS done right and these awesome working applications that we really need in the privacy space.

Session messaging which I use daily:
https://getsession.org/

Lokinet high-performance ONION network (similar to the darkweb but with lower latency for real-time voice and video comms) :
https://lokinet.org/

**Comment by mdPlusPlus** [comment]
OXEN the privacy coin does not exist anymore and will be succeeded by a non-private ERC token called SENT.
