### ISSUE TITLE
Wownero

### ISSUE THREAD

**Issue by djHenryStackz** [haveno-dex/listing#60]
### What's the ticker symbol of the project?
- WOW

### Why should it be added to Haveno? How would it benefit the project and the community?
- It's a Monero fork so privacy focused and this should make it easier as well?

### Is it an Ethereum token (ERC-20)?
- No
-
### Was the coin pre-mined before public launch?
- No

### Is there a dev fee for the project maintainers?
- No

### Please provide resources about the project (Website, Twitter, etc)
https://wownero.org

**Comment by mhhakim** [comment]
There is already an open issue about Wownero. #11

**Comment by djHenryStackz** [comment]
I see there is another request for Wownero :)
