### ISSUE TITLE
[Fiat] Add Israeli Shekels

### ISSUE THREAD

**Issue by Reproach721** [haveno-dex/listing#61]
- [x] I confirm there are no other open issues about this asset
- [x] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ISO code of the currency?

ILS

### Why should it be added to Haveno? How would it benefit the project and the community?
Israel has a population around 10 million people. ILS is also legal tender in the Palestinian territories, which has a population around 5 million people.
Israel doesn't have many crypto exchanges, and for most of them KYC is obligatory.

## Where is the currency used?
Israel and the Palestinian territories.

## Why would Haveno be beneficial for the people using this specific fiat currency?
Israelis and Palestinians can easily use Haveno and exhcnage with other Israelis and Palestinians.

### Additional notes
None.

**Comment by woodser** [comment]
All fiat currencies are already supported.
