### ISSUE TITLE
[Crypto] Add Firo

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#7]
Please consider down the road adding the ability to exchange between Monero and Firo.

Firo is a new privacy coin and will be as private as Monero when its lelantus protocol v2 is released.

**Comment by HavenoDEX** [comment]
This issue has been transferred to the [dedicated repository](https://github.com/haveno-dex/listing) for asset listing. Please edit the issue according to the correct [issue template](https://github.com/haveno-dex/listing/tree/master/.github/ISSUE_TEMPLATE)

**Comment by HavenoDEX** [comment]
No answer from the Author. Closing.
