### ISSUE TITLE
[Fiat] Add <cashapp>

### ISSUE THREAD

**Issue by XMRfamily** [haveno-dex/listing#73]
- [x ] I confirm there are no other open issues about this asset
- [ x] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ISO code of the currency?

USD, CAD, GBP

### Why should it be added to Haveno? How would it benefit the project and the community?
It is the most popular electronic payment method on localmonero and is needed to increase liquidity and popularity. Especially since haveno is supposed to fix fiat<->xmr issue

## Where is the currency used?
United States, Canada, UK

## Why would Haveno be beneficial for the people using this specific fiat currency?
Because localmonero shut down these people need a solution.

### Additional notes
Other payment methods need to be added that were on localmonero. I am in reto chat and they recommended us doing this

**Comment by XMRfamily** [comment]
Had to update that it's not EUR but GBP

**Comment by Rolandjg** [comment]
Cash app and similar apps like Venmo (maybe even Apple Pay and Google Pay) are definitely needed. There are some major risks involved with these payments so perhaps users should be shown a warning when selecting these methods.

**Comment by XMRZombie** [comment]
This issue should be closed since cashapp has been added

**Comment by woodser** [comment]
Cash App is supported now.
