### ISSUE TITLE
[Withdraw] Huge Withdrawal Rate 99%

### ISSUE THREAD

**Issue by gpsxpc** [haveno-dex/listing#74]
I want to take my XMR out of the Haveno wallet. And I was surprised by an absurd fee. Where 99% was a fee and 1% would only go to my wallet.

![image](https://github.com/haveno-dex/listing/assets/164305815/23116df4-7ea7-4455-a6f3-e030e2d56218)

**Comment by XMRfamily** [comment]
This issue was fixed. It was a ui bug for non English translations. The mining fee is not that high

**Comment by gpsxpc** [comment]
Thanks.
