### ISSUE TITLE
[Fiat] Add New Zealand Dollars

### ISSUE THREAD

**Issue by kayodde** [haveno-dex/listing#76]
- [X] I confirm there are no other open issues about this asset
- [X] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ISO code of the currency?
NZD

### Why should it be added to Haveno? How would it benefit the project and the community?
New Zealand has a population of over 5 million people as well as it being a member of the greater Anglosphere and a member of the Commonwealth, it is also listed on various other KYC exchanges. I would assume there is a moderately sized Monero community here.

## Where is the currency used?
New Zealand, as well as the Cook Islands, Niue and Tokelau

## Why would Haveno be beneficial for the people using this specific fiat currency?
New Zealanders can use Haveno to anonymously exchange cryptocurrency with other New Zealanders as well as people from overseas without having to worry about KYC or converting currency.

### Additional notes
N/A

**Comment by XMRZombie** [comment]
Already available, go in **Settings** and add NZD (this issue should be closed)
