### ISSUE TITLE
[Crypto] Add Haven

### ISSUE THREAD

**Issue by trymeouteh** [haveno-dex/listing#9]
Please consider down the road adding Haven protocol and all of its assets to be exchanged between Monero.

Haven is a private stablecoin platform built off of Moneros code.
https://havenprotocol.org/

**Comment by HavenoDEX** [comment]
This issue has been transferred to the [dedicated repository](https://github.com/haveno-dex/listing) for asset listing. Please edit the issue according to the correct [issue template](https://github.com/haveno-dex/listing/tree/master/.github/ISSUE_TEMPLATE)

**Comment by HavenoDEX** [comment]
No answer from the Author. Closing.
